services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - "9099:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-dashboard.json:/var/lib/grafana/dashboards/coupon-microservice.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - prometheus
    networks:
      - app_network

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"   # UI
      - "14250:14250"   # OTLP receiver
      - "9411:9411"     # Zipkin
      - "14268:14268"   # Thrift
      - "4318:4318"
      - "4317:4317"
    networks:
      - app_network


  # Node exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - app_network

  mysql-exporter-rule-service:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter-rule-service
    ports:
      - "9104:9104"
    command:
      - "--mysqld.username=root:123456"
      - "--mysqld.address=rule_mysql:3306"
    networks:
      - app_network

  mysql-exporter-coupon-service:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter-coupon-service
    ports:
      - "9105:9104"
    command:
      - "--mysqld.username=root:123456"
      - "--mysqld.address=coupon_mysql:3306"
    networks:
      - app_network

  mysql-exporter-order-service:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter-order-service
    ports:
      - "9106:9104"
    command:
      - "--mysqld.username=root:123456"
      - "--mysqld.address=order_mysql:3306"
    networks:
      - app_network

  redis-exporter-rule-service:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter-rule-service
    ports:
      - "9122:9121"
    environment:
      - REDIS_ADDR=redis://rule_redis:6379
    networks:
      - app_network

  redis-exporter-coupon-service:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter-coupon-service
    ports:
      - "9123:9121"
    environment:
      - REDIS_ADDR=redis://coupon_redis:6379
    networks:
      - app_network

  redis-exporter-order-service:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter-order-service
    ports:
      - "9124:9121"
    environment:
      - REDIS_ADDR=redis://order_redis:6379
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.21
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - app_network


volumes:
  grafana_data:
  prometheus_data:
  esdata:
networks:
  app_network:
    external: true
